Remove unnecessary .quit() call on Joy class causing exceptions on shutdown in arc_arena
Exception at shutdown:
pygame.error: joystick system not initialized